steps:
- id: 'fetch-secrets'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$$(gcloud secrets versions access latest --secret=CLERK_PK --format='ge' | tr -d '\n' | base64 --decode)

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  env:
  - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuanVudGVyLm5sJA'
  - 'CLERK_SECRET_KEY=sk_live_AseQfBAHQjInOqHTupuqKrUYXVZI4oCCU04WIZpeST'

options:
  logging: CLOUD_LOGGING_ONLY


