# steps:
# - id: 'fetch-secrets'
#   name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$$(gcloud secrets versions access latest --secret=CLERK_PK --format='ge' | tr -d '\n' | base64 --decode)

# steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['ci']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'build']
#   env:
#   - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuanVudGVyLm5sJA'
#   - 'CLERK_SECRET_KEY=sk_live_AseQfBAHQjInOqHTupuqKrUYXVZI4oCCU04WIZpeST'

# options:
#   logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/CLERK_PK/versions/latest
      env: "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
    - versionName: projects/$PROJECT_ID/secrets/CLERK_SK/versions/latest
      env: "CLERK_SECRET_KEY"

steps:
  - id: "npm-ci"
    name: "node:20-bookworm"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        npm ci

  - id: "next-build"
    name: "node:20-bookworm"
    entrypoint: "bash"
    secretEnv:
      - "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
      - "CLERK_SECRET_KEY"
    args:
      - "-c"
      - |
        set -euo pipefail
        # Build-time env for Next.js
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_live_Y2xlcmsuanVudGVyLm5sJA" \
        CLERK_SECRET_KEY="sk_live_AseQfBAHQjInOqHTupuqKrUYXVZI4oCCU04WIZpeST" \
        npm run build

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"



